In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix, accuracy_score, precision_recall_fscore_support
from sklearn.metrics import roc_auc_score

In [2]:
dataset = pd.read_csv('../data/datasets/1.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [3]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state=0)
# Use random state or cross validation to maintain consistency for test training data

In [4]:
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [5]:
classifier = LogisticRegression(random_state = 0)
classifier.fit(X_train, y_train)

LogisticRegression(random_state=0)

In [6]:
y_pred = classifier.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)


[[136  14]
 [  1 137]]


0.9479166666666666

In [7]:
precision_recall_fscore_support(y_test, y_pred)

(array([0.99270073, 0.90728477]),
 array([0.90666667, 0.99275362]),
 array([0.94773519, 0.94809689]),
 array([150, 138]))

In [8]:
clf = LogisticRegression(solver="liblinear", random_state=0).fit(X_test, y_test)
roc_auc_score(y_test, clf.predict_proba(X_test)[:, 1])

0.9996618357487922

In [9]:
print(clf.coef_, clf.intercept_)

[[-0.46379465  0.11065208  0.26498561  0.2084819  -0.04494247  0.08685803
  -0.41665897 -0.20665293  0.0453728   0.10333279 -0.46985272 -0.20793207
   0.27300601 -0.11148845 -0.15761356  0.00599153 -0.00599153  0.00599153
   0.00599153  0.00599153  0.13223201  0.00599153  0.00599153  0.0954647
   0.6414574   0.17605915  0.00847822  0.00599153  0.00847822  0.00599153
   0.05254068  0.1213602   0.00599153  0.00599153  0.00599153  0.10531631
   0.21346473  0.12973089  0.00599153  0.00599153  0.12254878  0.00599153
   0.30164377  0.18811786  0.00599153  0.00599153  0.00599153  0.2383488
   0.00599153  0.00599153  0.00599153  0.08537035  0.00599153  0.00599153
   0.21618819  0.0103897   0.34576364  0.09400315  0.00599153  0.01200397
   0.50970465  0.00599153  0.00599153  0.14537581  0.0103897   0.19198304
   0.00599153  0.00599153  0.25449532  0.0103897   0.0103897   0.00599153
   0.00599153  0.00847822  0.08949311  0.19346366  0.00599153  0.00599153
   0.18624214  0.00599153  0.00388835  0